### ISSUE TITLE
Passport Mock

### ISSUE THREAD

**Issue by guyellis** [passport-next/passport#2]
This is a discussion topic, not an issue.

First off - thanks so much @rwky for forking these repos into `.../passport-next/...` and publishing them!

I was wondering if this passport-next org would be the right place to create and publish a passport-mock module to help with testing?

I found https://github.com/shake-apps/passport-mocked but that seems to be stale.

Thoughts?

**Comment by rwky** [comment]
That's a good idea! I could probably do with using a module like that myself. Leave it with me.

**Comment by guyellis** [comment]
Thanks so much @rwky 

Looking at that `passport-mocked` module I'm not a fan of how the module is included in the production code and required based on NODE_ENV. I think that the mocks should stay out of prod code and be swapped in during testing.

What test framework do you use? My favorite is `jest`. With the jest syntax I'd love to be able to do something like:

```javascript
const mockPassport = require('@passport-next/passport-mock');
jest.mock('passport', () => mockPassport);
```

**Comment by rwky** [comment]
Never used jest normally we use mocha/chai never used jest. As for the NODE_ENV I can see that being a useful method but not a required one. For test suites you'd just require the mock module instead of whatever module you'd use during live and that should do the trick.

**Comment by guyellis** [comment]
This is complete.
