### ISSUE TITLE
Lint standardisation for @passport-next

### ISSUE THREAD

**Issue by guyellis** [passport-next/passport#3]
We should standardise on a linter and lint rules to make the style consistent across all repos in @passport-next.

I'll kick off with suggesting ESLint and the Airbnb Rules. WDYT?

**Comment by rwky** [comment]
Sounds good to me on both accounts.

**Comment by guyellis** [comment]
Closing for now. Don't let this stop anybody from adding a comment to build on and improve this.

**Comment by rwky** [comment]
FYI I've started working on this in the eslint branch

**Comment by brettz9** [comment]
Can the jshint rules be removed?
