### ISSUE TITLE
2FA for GitHub and Npm

### ISSUE THREAD

**Issue by guyellis** [passport-next/passport#4]
@rwky as an owner of the `passport-next` org you can [check to see who has GitHub 2FA enabled](https://help.github.com/articles/viewing-whether-users-in-your-organization-have-2fa-enabled/) and encourage members of the org to have it enabled. Also you can consider having a policy of having members of this org enable 2FA.

Given that we're dealing with authentication in these modules I feel that 2FA is more important here than it might be in other areas.

Also, I'm guessing that you're the only one with Npm publish rights for this org. I'd suggest a similar 2FA policy for Npm accounts that can publish these modules.

**Comment by rwky** [comment]
I already enforce 2FA for github and for NPM (I'm the only one that can push to NPM at the moment though at some point that'll change just in case I get hit by a bus). I also gpg sign all tags. I have a healthy amount of paranoia so if you can think of anything else to enhance security just yell.

**Comment by guyellis** [comment]
How do you enforce 2FA for GitHub?

**Comment by rwky** [comment]
There's an option in the org settings.

![screenshot at 2018-08-13 15 07 13](https://user-images.githubusercontent.com/151715/44036805-9a7fbfa6-9f0a-11e8-98d9-6f876afc6566.png)
