### ISSUE TITLE
Add Linting

### ISSUE THREAD

**Issue by guyellis** [passport-next/passport#8]
Add Linting to the project.

[This PR](https://github.com/passport-next/passport-mocked/pull/4/files) is a good example of how to do it.

Start by adding the same `.eslintrc.js` and then make the same or similar changes to the `package.json` file.

Then run `npm run lintfix`.

Now manually fix the errors that the linter was unable to fix automatically.

PR and profit.

**Comment by rwky** [comment]
I've already got some of this going in the eslint branch. Just re-pushed it and tagged this issue in it. The promises issue gives me greater reason to finish this :smile:

**Comment by rwky** [comment]
Closed via #10

**Comment by guyellis** [comment]
@rwky - why did this PR cause the version to be a major bump?

**Comment by rwky** [comment]
From the commit

> * Making SEMVER change due to massive code changes from linting even though nothing else should change

Basically it's me being a little paranoid and giving a warning to users saying "hey this should work the same but due to the massive changes you never know"

**Comment by guyellis** [comment]
@rwky I understand and love the paranoia.

I think that version changes should accurately communicate what's happening when we publish a version. If there is nothing breaking then it should be minor or patch. Because there were no new features it should have been a patch.

I don't think we should be redefining how semver works to make users pay more attention.

If we start using "size of change" by number of lines changed or % changed then we have to start defining what % warrants a major etc. as this might not be the last massive change that's made.

**Comment by rwky** [comment]
This is a rare case. If we strictly followed semver then this would have been a patch. I wouldn't have felt comfortable releasing such a massive change with potential breakage on a patch release. IMHO it's better to release as a major when there are no known breaking changes then to release as a patch when there could be unknown breaking changes.

**Comment by guyellis** [comment]
I added this. WDYT? https://github.com/passport-next/passport/pull/12
I'm thinking about future visitors and want to avoid confusion and misunderstanding by being transparent and obvious.

**Comment by rwky** [comment]
Sounds good to me!
